services:
  - type: web
    name: pcos-prediction
    env: python
    repo: https://github.com/ashsub2005/solveathon
    branch: main
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PORT
        value: 8501
